# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build And Publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh
    

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Netizine.OpenAI
      run: dotnet build --no-restore
    - name: Install OpenAI.Mock
      run: dotnet tool install --global OpenAI.Mock 
    - name: Run Tests
      run: dotnet test --no-restore --no-build --configuration Release
    - name: Pack Nuget
      run: dotnet pack src/Netizine.OpenAI/Netizine.OpenAI.csproj --no-build --verbosity normal --output nupkgs
    - name: Get Version
      uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
      id: get-version
      with:
          proj-path: src/Netizine.OpenAI/Netizine.OpenAI.csproj
    - name: Install Nuget Validator
      run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.304
    - name: Validate Nuget Package
      run: dotnet validate package local "nupkgs/Netizine.OpenAI.${{steps.get-version.outputs.version}}.nupkg"
    - name: Publish NuGet Package
      run: dotnet nuget push "nupkgs/Netizine.OpenAI.${{steps.get-version.outputs.version}}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish NuGet Package to Github
      run: dotnet nuget push "nupkgs/Netizine.OpenAI.${{steps.get-version.outputs.version}}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.pkg.github.com/NAMESPACE/index.json --skip-duplicate
